ai_content_summary.settings:
  type: config_object
  label: "AI Content Summary settings"
  mapping:
    prompt:
      type: text
      label: "AI Summary Prompt"
    max_length:
      type: integer
      label: "Maximum Summary Length"
    min_length:
      type: integer
      label: "Minimum Summary Length"
    view_mode:
      type: string
      label: "View Mode for Content Extraction"
    enabled_types:
      type: sequence
      label: "Enabled Content Types"
      sequence:
        type: string
